"""
nginx reverse proxy management for Jupyter instances.

When NGINX_ENABLED=true, each Jupyter instance gets a dedicated nginx server
block that maps a human-readable hostname to the real node IP + port:

    http://A100.jup-20260729-abc123/lab  →  http://10.6.12.17:37975

Config files are written to NGINX_CONF_DIR and nginx is reloaded via
NGINX_RELOAD_CMD after every write/remove.

Clients must point their DNS to the master node where dnsmasq is running.
dnsmasq resolves all unknown hostnames to the master node IP (nginx).

One-time setup on master node:
    apt install nginx dnsmasq
    # /etc/dnsmasq.conf — append:
    server=8.8.8.8
    server=8.8.4.4
    address=/.aistudio/<master-node-ip>   # only intercepts *.aistudio hostnames
    systemctl enable --now dnsmasq

Clients: set master node IP as primary DNS in network settings.
"""

import logging
import os
import subprocess

from app.config import settings

logger = logging.getLogger(__name__)

_TEMPLATE = """\
# Auto-generated by aistudio-server — DO NOT EDIT MANUALLY
# Jupyter proxy for task: {task_id}
server {{
    listen 80;
    server_name {hostname};

    # WebSocket support (required for Jupyter kernel communication)
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 86400;

    location / {{
        proxy_pass http://{node_ip}:{port};
    }}
}}
"""


def proxy_url(gpu_type: str, task_id: str) -> str:
    """Return the proxy URL for a Jupyter instance, e.g. http://A100.jup-20260729-abc123.aistudio/lab"""
    return "http://%s.%s.aistudio/lab" % (gpu_type.upper(), task_id)


def write_jupyter_config(task_id: str, gpu_type: str, node_ip: str, port: int) -> None:
    """
    Write an nginx server block for this Jupyter instance and reload nginx.
    No-op if NGINX_ENABLED is false.
    Raises on failure so the caller can decide whether to abort or continue.
    """
    if not settings.NGINX_ENABLED:
        return

    hostname = "%s.%s.aistudio" % (gpu_type.upper(), task_id)
    conf = _TEMPLATE.format(
        task_id=task_id,
        hostname=hostname,
        node_ip=node_ip,
        port=port,
    )
    path = _conf_path(task_id)
    try:
        with open(path, "w") as f:
            f.write(conf)
        logger.info("nginx: config written for %s → http://%s:%d", hostname, node_ip, port)
    except Exception as exc:
        logger.error("Failed to write nginx config for %s: %s", task_id, exc)
        raise

    # Reload nginx — best-effort, never fail the Jupyter launch
    try:
        _reload_nginx()
    except Exception as exc:
        logger.warning("nginx reload failed for %s (config written, reload manually): %s", task_id, exc)


def remove_jupyter_config(task_id: str) -> None:
    """
    Remove the nginx server block for this instance and reload nginx.
    Silent no-op if the file doesn't exist or NGINX_ENABLED is false.
    """
    if not settings.NGINX_ENABLED:
        return

    path = _conf_path(task_id)
    try:
        if os.path.exists(path):
            os.remove(path)
            _reload_nginx()
            logger.info("nginx: config removed for %s", task_id)
    except Exception as exc:
        logger.warning("Failed to remove nginx config for %s: %s", task_id, exc)


def _conf_path(task_id: str) -> str:
    return os.path.join(settings.NGINX_CONF_DIR, "jupyter-%s.conf" % task_id)


def _reload_nginx() -> None:
    # shell=True so NGINX_RELOAD_CMD can be a full shell string, e.g.:
    # "ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no kube@10.6.12.13 sudo nginx -s reload"
    result = subprocess.run(
        settings.NGINX_RELOAD_CMD,
        shell=True,
        capture_output=True,
        text=True,
        timeout=10,
    )
    if result.returncode != 0:
        raise RuntimeError("nginx reload failed: %s" % result.stderr.strip())
