"""
nginx reverse proxy management for Jupyter instances.

When NGINX_ENABLED=true, each Jupyter instance gets a path-based nginx route:

    http://corespan.ddnsgeek.com/jupyter/T4/jup-20260729-abc123/lab
      → http://10.6.12.26:37975/

No DNS setup required — uses the public domain configured in PROXY_BASE_URL.

How it works
────────────
1. A single base nginx server block lives at:
       /etc/nginx/conf.d/aistudio-jupyter.conf
   It listens on port 80 and includes all per-instance location files:
       include /etc/nginx/jupyter-locations/*.conf;

2. Each Jupyter launch writes one location file:
       /etc/nginx/jupyter-locations/jupyter-{task_id}.conf
   containing a single `location /jupyter/{GPU_TYPE}/{task_id}/ { ... }` block.

3. nginx is reloaded after every write/remove via NGINX_RELOAD_CMD.

One-time setup on master node (run as root/sudo, do this once)
──────────────────────────────────────────────────────────────
    sudo apt install nginx
    sudo mkdir -p /etc/nginx/jupyter-locations

    sudo tee /etc/nginx/conf.d/aistudio-jupyter.conf << 'EOF'
    server {
        listen 80;
        server_name _;
        include /etc/nginx/jupyter-locations/*.conf;
    }
    EOF

    sudo nginx -t && sudo systemctl reload nginx

Then in .env set:
    NGINX_ENABLED=true
    PROXY_BASE_URL=http://corespan.ddnsgeek.com
    NGINX_CONF_DIR=/etc/nginx/jupyter-locations
    NGINX_RELOAD_CMD=ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no kube@10.6.12.15 sudo nginx -s reload

And in docker-compose.yml mount the locations dir into the worker:
    - /etc/nginx/jupyter-locations:/etc/nginx/jupyter-locations

Note on Jupyter base URL
────────────────────────
For JupyterLab to work correctly behind a subpath proxy, the container must be
started with --ServerApp.base_url=/jupyter/{GPU_TYPE}/{task_id}/.
ManifestBuilder.build_jupyter_command() passes this as the JUPYTER_BASE_URL env var.
The container's startJupyter.py must honour it:

    import os
    base_url = os.environ.get("JUPYTER_BASE_URL", "/")
    # then pass  --ServerApp.base_url={base_url}  to the jupyter lab command
"""

import logging
import os
import subprocess

from app.config import settings

logger = logging.getLogger(__name__)

_LOCATION_TEMPLATE = """\
# Auto-generated by aistudio-server — DO NOT EDIT MANUALLY
# Jupyter proxy for task: {task_id}
# GPU: {gpu_type}  →  {node_ip}:{port}
location /jupyter/{gpu_type}/{task_id}/ {{
    proxy_pass http://{node_ip}:{port}/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 86400;
}}
"""


def proxy_url(gpu_type: str, task_id: str) -> str:
    """
    Return the public proxy URL for a Jupyter instance.
    e.g. http://corespan.ddnsgeek.com/jupyter/T4/jup-20260729-abc123/lab
    Falls back to empty string if PROXY_BASE_URL is not set.
    """
    base = settings.PROXY_BASE_URL.rstrip("/")
    if not base:
        return ""
    return "%s/jupyter/%s/%s/lab" % (base, gpu_type.upper(), task_id)


def jupyter_base_path(gpu_type: str, task_id: str) -> str:
    """
    Return the subpath that Jupyter must be told to run under via --ServerApp.base_url.
    e.g. /jupyter/T4/jup-20260729-abc123/
    """
    return "/jupyter/%s/%s/" % (gpu_type.upper(), task_id)


def write_jupyter_config(task_id: str, gpu_type: str, node_ip: str, port: int) -> None:
    """
    Write an nginx location block for this Jupyter instance and reload nginx.
    No-op if NGINX_ENABLED is false.
    Logs a warning (never raises) if the directory is missing or reload fails,
    so that a nginx misconfiguration never blocks a Jupyter launch.
    """
    if not settings.NGINX_ENABLED:
        return

    conf = _LOCATION_TEMPLATE.format(
        task_id=task_id,
        gpu_type=gpu_type.upper(),
        node_ip=node_ip,
        port=port,
    )
    path = _conf_path(task_id)
    try:
        os.makedirs(settings.NGINX_CONF_DIR, exist_ok=True)
        with open(path, "w") as f:
            f.write(conf)
        logger.info(
            "nginx: location written  /jupyter/%s/%s/  →  http://%s:%d",
            gpu_type.upper(), task_id, node_ip, port,
        )
    except Exception as exc:
        logger.error("Failed to write nginx location config for %s: %s", task_id, exc)
        return  # don't try to reload if the write failed

    try:
        _reload_nginx()
    except Exception as exc:
        logger.warning(
            "nginx reload failed for %s (location file written, reload manually): %s",
            task_id, exc,
        )


def remove_jupyter_config(task_id: str) -> None:
    """
    Remove the nginx location block for this instance and reload nginx.
    Silent no-op if the file doesn't exist or NGINX_ENABLED is false.
    """
    if not settings.NGINX_ENABLED:
        return

    path = _conf_path(task_id)
    try:
        if os.path.exists(path):
            os.remove(path)
            logger.info("nginx: location removed for %s", task_id)
            try:
                _reload_nginx()
            except Exception as exc:
                logger.warning("nginx reload failed after removing %s: %s", task_id, exc)
    except Exception as exc:
        logger.warning("Failed to remove nginx config for %s: %s", task_id, exc)


def _conf_path(task_id: str) -> str:
    return os.path.join(settings.NGINX_CONF_DIR, "jupyter-%s.conf" % task_id)


def _reload_nginx() -> None:
    # shell=True lets NGINX_RELOAD_CMD be a full shell string, e.g.:
    # "ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no kube@10.6.12.15 sudo nginx -s reload"
    result = subprocess.run(
        settings.NGINX_RELOAD_CMD,
        shell=True,
        capture_output=True,
        text=True,
        timeout=10,
    )
    if result.returncode != 0:
        raise RuntimeError("nginx reload failed: %s" % result.stderr.strip())
