"""initial_schema

Revision ID: f0e43419bf9b
Revises: 
Create Date: 2026-06-04 09:39:27.808494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0e43419bf9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_results',
    sa.Column('id', sa.UUID(), nullable=False, comment='Internal surrogate key.'),
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='Runner-assigned run identifier. Unique per logical benchmark run.'),
    sa.Column('sub_run_index', sa.Integer(), nullable=False, comment='Index within a sweep run. 0 for single runs.'),
    sa.Column('model_name', sa.String(length=128), nullable=False, comment="LLM model identifier. e.g. 'llama3-8b-instruct'. Always lowercase."),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False, comment="Version of the inference pipeline. e.g. 'vllm-0.4.2'."),
    sa.Column('node_ips', postgresql.ARRAY(sa.Text()), nullable=False, comment="IP addresses of GPU nodes used. Single node: ['10.6.12.15']."),
    sa.Column('gpu_type', sa.String(length=16), nullable=False, comment="GPU family. e.g. 'a100', 'h100', 't4'. Always lowercase."),
    sa.Column('gpu_count', sa.Integer(), nullable=False, comment='Number of GPUs used across all nodes.'),
    sa.Column('gpu_model', sa.String(length=64), nullable=True, comment="Full GPU model string from nvidia-smi. e.g. 'NVIDIA A100-SXM4-80GB'."),
    sa.Column('precision', sa.String(length=16), nullable=False, comment="Model precision. e.g. 'fp16', 'bf16', 'int4'. Always lowercase."),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='Input prompt token count used in the benchmark.'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='Max output token count used in the benchmark.'),
    sa.Column('concurrency', sa.Integer(), nullable=False, comment='Number of concurrent requests sent to the inference server.'),
    sa.Column('status', sa.String(length=16), nullable=False, comment="Execution result. 'success' or 'failed'."),
    sa.Column('total_token_throughput', sa.Float(), nullable=True, comment='Total tokens/sec across all concurrent requests. Primary leaderboard sort key.'),
    sa.Column('mean_ttft_ms', sa.Float(), nullable=True, comment='Mean Time To First Token in milliseconds.'),
    sa.Column('mean_tpot_ms', sa.Float(), nullable=True, comment='Mean Time Per Output Token in milliseconds.'),
    sa.Column('mean_e2el_ms', sa.Float(), nullable=True, comment='Mean end-to-end latency per request in milliseconds.'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full raw metrics payload from the runner. No schema enforced.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='When the benchmark execution started on the node.'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When the benchmark execution completed. Null if still running or failed mid-run.'),
    sa.Column('duration_seconds', sa.Float(), nullable=True, comment='Total wall-clock execution time in seconds.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was inserted into the database.'),
    sa.CheckConstraint('gpu_type = lower(gpu_type)', name='ck_gpu_type_lower'),
    sa.CheckConstraint('model_name = lower(model_name)', name='ck_model_name_lower'),
    sa.CheckConstraint('precision = lower(precision)', name='ck_precision_lower'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sub_run_index', name='uq_benchmark_run_sub')
    )
    op.create_index(op.f('ix_benchmark_results_concurrency'), 'benchmark_results', ['concurrency'], unique=False)
    op.create_index(op.f('ix_benchmark_results_gpu_type'), 'benchmark_results', ['gpu_type'], unique=False)
    op.create_index(op.f('ix_benchmark_results_model_name'), 'benchmark_results', ['model_name'], unique=False)
    op.create_index(op.f('ix_benchmark_results_run_id'), 'benchmark_results', ['run_id'], unique=False)
    op.create_table('workload_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment="Internal identifier for the workload type. e.g. 'LLMInference'."),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment="Human-readable name shown in the UI. e.g. 'LLM Inference'."),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of what this workload type does.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workload_types_name'), 'workload_types', ['name'], unique=True)
    op.create_table('workloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workload_id', sa.String(length=30), nullable=False, comment='Human-readable ID returned to the UI as task_id.'),
    sa.Column('model_name', sa.String(length=128), nullable=False, comment="LLM model to benchmark. e.g. 'llama3-8b-instruct'."),
    sa.Column('workload_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='User-submitted benchmark configuration from the start request.'),
    sa.Column('state', sa.Enum('CREATED', 'VALIDATING', 'VALIDATED', 'INSTALLING', 'READY', 'RUNNING', 'FAILED', name='workload_state'), nullable=False, comment='Current lifecycle state. Driven by the Celery chain.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error detail if state is FAILED.'),
    sa.Column('workload_port', sa.Integer(), nullable=True, comment='Port the inference server listens on.'),
    sa.Column('communication_port', sa.Integer(), nullable=True, comment='Port used for internal communication with the node agent.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Updated automatically on every state transition.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workloads_state'), 'workloads', ['state'], unique=False)
    op.create_index(op.f('ix_workloads_workload_id'), 'workloads', ['workload_id'], unique=True)
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workload_id', sa.UUID(), nullable=False, comment='The workload this node is assigned to.'),
    sa.Column('machine_id', sa.String(length=30), nullable=False, comment="Short human-readable node identifier. e.g. 'node-a3f9bc'."),
    sa.Column('machine_ip', sa.String(length=45), nullable=False, comment='IP address used to SSH into this node.'),
    sa.Column('machine_username', sa.String(length=30), nullable=False, comment='SSH username. Configured via SSH_DEFAULT_USER in .env.'),
    sa.Column('state', sa.Enum('ADDED', 'VALIDATING', 'VALIDATED', 'INSTALLING', 'READY', 'RUNNING', 'FAILED', name='node_state'), nullable=False, comment='Current lifecycle state of this node.'),
    sa.Column('sw_installed', sa.Boolean(), nullable=False, comment='True once dependencies have been installed on this node.'),
    sa.Column('gpus', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='GPU inventory collected from nvidia-smi during validation.'),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full hardware spec dict: CPU, RAM, disk, CUDA version etc.'),
    sa.Column('pcie_tree', sa.Text(), nullable=True, comment='Raw output of nvidia-smi topo -m for this node.'),
    sa.Column('heartbeat_interval', sa.Integer(), nullable=False, comment='Seconds between heartbeat checks during benchmark execution.'),
    sa.Column('hb_error_count', sa.Integer(), nullable=False, comment='Consecutive missed heartbeats. Triggers FAILED state when threshold hit.'),
    sa.Column('running_task', sa.String(length=50), nullable=True, comment='workload_id of the task currently executing on this node. Null if idle.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workload_id'], ['workloads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_state'), 'nodes', ['state'], unique=False)
    op.create_index(op.f('ix_nodes_workload_id'), 'nodes', ['workload_id'], unique=False)
    op.create_table('workload_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workload_id', sa.UUID(), nullable=False, comment='The workload this event belongs to.'),
    sa.Column('state', sa.String(length=20), nullable=False, comment='Workload state at the time of this event.'),
    sa.Column('trigger', sa.String(length=50), nullable=False, comment='Celery task name or internal trigger that wrote this event.'),
    sa.Column('message', sa.Text(), nullable=False, comment='Log message shown to the user in the SSE stream.'),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this event was recorded. Set by the database server.'),
    sa.ForeignKeyConstraint(['workload_id'], ['workloads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workload_events_workload_id'), 'workload_events', ['workload_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workload_id', sa.UUID(), nullable=False, comment='The workload this task belongs to.'),
    sa.Column('node_id', sa.UUID(), nullable=True, comment='The node this task ran on. SET NULL if the node is deleted.'),
    sa.Column('run_name', sa.String(length=100), nullable=False, comment='Human-readable run identifier. Also used as run_id in BenchmarkResult.'),
    sa.Column('task_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Exact benchmark config used for this run. Snapshot from workload_config.'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Execution status: 'running', 'success', 'failed'."),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the execute_benchmark Celery task started.'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When execution finished. Null while still running.'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workload_id'], ['workloads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_run_name'), 'tasks', ['run_name'], unique=True)
    op.create_index(op.f('ix_tasks_workload_id'), 'tasks', ['workload_id'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='The task this log line belongs to.'),
    sa.Column('line', sa.Text(), nullable=False, comment='Single log line from the SSH session stdout/stderr.'),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this log line was inserted. Used for SSE cursor-based streaming.'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_logged_at'), 'task_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_logged_at'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_tasks_workload_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_run_name'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_workload_events_workload_id'), table_name='workload_events')
    op.drop_table('workload_events')
    op.drop_index(op.f('ix_nodes_workload_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_state'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_workloads_workload_id'), table_name='workloads')
    op.drop_index(op.f('ix_workloads_state'), table_name='workloads')
    op.drop_table('workloads')
    op.drop_index(op.f('ix_workload_types_name'), table_name='workload_types')
    op.drop_table('workload_types')
    op.drop_index(op.f('ix_benchmark_results_run_id'), table_name='benchmark_results')
    op.drop_index(op.f('ix_benchmark_results_model_name'), table_name='benchmark_results')
    op.drop_index(op.f('ix_benchmark_results_gpu_type'), table_name='benchmark_results')
    op.drop_index(op.f('ix_benchmark_results_concurrency'), table_name='benchmark_results')
    op.drop_table('benchmark_results')
    # ### end Alembic commands ###
